"""Initial Migration

Revision ID: c0192ce5b2dc
Revises: 
Create Date: 2026-01-10 11:29:24.732616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0192ce5b2dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('course_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('estudent_id', sa.Integer(), nullable=False),
    sa.Column('ecourse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecourse_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['estudent_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
